// user-interface/src/app/steps/generation/generation.component.ts
import { SettingsStepService } from '../../service/settings-step.service';
import { Component, OnInit } from '@angular/core';
import { StepComponent } from '../step.component';
import { StepCompletion } from 'src/app/model/step-completion';
import { NavigationDirection } from 'src/app/model/navigation-direction';
import { Step } from 'src/app/model/step';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'app-generation',
  templateUrl: './generation.component.html',
  styleUrls: ['./generation.component.css']
})
export class GenerationComponent extends StepComponent {

  generationForm: FormGroup;

  constructor(private formBuilder: FormBuilder, private settingsStepService: SettingsStepService) {
    super();
    this.createForm();
  }

  ngOnInit(): void {
  }

  createForm() {
    this.generationForm = this.formBuilder.group({
      projectDirectory: ['', Validators.required],
      useAnnotations: [false, Validators.required],
      useAutoDispatch: [false, Validators.required]
    });
  }

  generate() {
    const value = this.generationForm.value;
    this.settingsStepService.addGenerationData(value.projectDirectory, value.useAnnotations, value.useAutoDispatch);
    this.settingsStepService.getSettings$.subscribe(a => console.log(a));
    this.stepCompletion.emit(new StepCompletion(
      Step.GENERATION,
      this.generationForm.valid,
      NavigationDirection.FINISH
    ));
  }

  onAnnotationsClick($event) {
    this.generationSettings.useAnnotations = $event.target.checked;
    if(!this.generationSettings.useAnnotations) {
      this.generationSettings.useAutoDispatch = false;
    }
  }

  onAutoDispatchClick($event) {
    this.generationSettings.useAutoDispatch = $event.target.checked;
  }

  next(): void {
    throw new Error('Operation Not Supported.');
  }

  previous(): void {
    this.stepCompletion.emit(new StepCompletion(
      Step.GENERATION,
      this.generationForm.valid,
      NavigationDirection.REWIND
    ));
  }

  hasNext(): Boolean {
    return false;
  }

  hasPrevious(): Boolean {
    return true;
  }

  isLastStep() : Boolean {
    return true;
  }

}

<app-step-title title="Generation"></app-step-title>

<form [formGroup]="generationForm">
    <div class="form-group col-md-4">
        <label for="projectDirectory">Where do you want to generate the project?</label>
        <input type="text" class="form-control starter-field"
        id="projectDirectory"
        formControlName="projectDirectory"
        placeholder="Absolute path for the new xoom project">
    </div>

    <div class="form-row xoom-annotations">
        <div class="col-md-3">
            <label for="useAnnotations">Use VLINGO/XOOM annotations:</label>
        </div>
        <div class="col-md-1 pt-1">
            <input type="checkbox"
            class="form-check-input"
            formControlName="useAnnotations"
            (click)="onAnnotationsClick($event)">
        </div>
    </div>

    <div class="form-row xoom-annotations">
        <div class="col-md-3">
            <label for="useAutoDispatch">Use VLINGO/XOOM auto dispatch:</label>
        </div>
        <div class="col-md-1 pt-1">
            <input type="checkbox"
            class="form-check-input"
            (click)="onAutoDispatchClick($event)"
            formControlName="useAutoDispatch"
            [disabled]="!generationSettings.useAnnotations">
        </div>
    </div>
</form>

// src/main/frontend/src/routes/generation.svelte
<script>
	import Switch from "svelte-materialify/src/components/Switch";
	import TextField from "svelte-materialify/src/components/TextField";
	import CardForm from "../components/CardForm.svelte";
	import { contextSettings, aggregateSettings, persistenceSettings, deploymentSettings, generationSettings } from "../stores";

	let context = $contextSettings;
    let model = { aggregateSettings: $aggregateSettings, persistenceSettings: $persistenceSettings};
    let deployment  = $deploymentSettings;
    let projectDirectory = $generationSettings ? $generationSettings.projectDirectory : "";
    let useAnnotations = $generationSettings ? $generationSettings.useAnnotations : false;
	let useAutoDispatch = $generationSettings ? $generationSettings.useAutoDispatch : false;

	$: if(!useAnnotations) useAutoDispatch = false;

	$: $generationSettings = { context, model, deployment, projectDirectory, useAnnotations, useAutoDispatch }
	$: console.log($generationSettings);
</script>

<!-- add newbie tooltips -->
<CardForm title="Generation" previous="deployment">
	<TextField placeholder="D:\demo-projects" bind:value={projectDirectory}>Absolute path where you want to generate the project</TextField>
	<Switch bind:checked={useAnnotations}>Use VLINGO/XOOM annotations</Switch>
	<Switch bind:checked={useAutoDispatch} disabled={!useAnnotations}>Use VLINGO/XOOM auto dispatch</Switch>
</CardForm>
