// user-interface/src/app/steps/model/persistence/persistence.component.ts
import {
  Persistence,
  Model
} from './../../../model/model-aggregate';
import {
  SettingsStepService
} from '../../../service/settings-step.service';
import {
  FormGroup,
  FormBuilder,
  Validators
} from '@angular/forms';
import {
  NavigationDirection
} from 'src/app/model/navigation-direction';
import {
  Step
} from 'src/app/model/step';
import {
  Component,
  OnInit
} from '@angular/core';
import {
  StepComponent
} from '../../step.component';
import {
  StepCompletion
} from 'src/app/model/step-completion';

@Component({
  selector: 'app-persistence',
  templateUrl: './persistence.component.html',
  styleUrls: ['./persistence.component.css']
})
export class PersistenceComponent extends StepComponent implements OnInit {

  persistenceForm: FormGroup;
  projections;
  storageTypes = [{
      name: 'State Store',
      value: 'STATE_STORE'
    },
    {
      name: 'Journal',
      value: 'JOURNAL'
    }
  ];
  databases = [{
      name: 'In Memory',
      value: 'IN_MEMORY'
    },
    {
      name: 'Postgres',
      value: 'POSTGRES'
    },
    {
      name: 'HSQLDB',
      value: 'HSQLDB'
    },
    {
      name: 'MySQL',
      value: 'MYSQL'
    },
    {
      name: 'YugaByte',
      value: 'YUGA_BYTE'
    }
  ];


  constructor(private formBuilder: FormBuilder, private settingsStepService: SettingsStepService) {
    super();
    settingsStepService.getSettings$.subscribe(settings => {
      this.createNewForm(settings.model);
    });
  }

  ngOnInit(): void {
    this.persistenceForm.get('storageType').valueChanges.subscribe(value => {
      this.defineProjections(value);
    });
  }

  createNewForm(model: Model) {
    const persistence = (model && model.persistenceSettings) ? model.persistenceSettings : {} as Persistence;
    this.persistenceForm = this.formBuilder.group({
      storageType: [persistence.storageType, [Validators.required]],
      useCQRS: [!!persistence.useCQRS, [Validators.required]],
      projections: [persistence.projections, [Validators.required]],
      database: [persistence.database, []],
      commandModelDatabase: [persistence.commandModelDatabase, []],
      queryModelDatabase: [persistence.queryModelDatabase, []],
    });
    this.defineProjections(persistence.storageType);
  }

  next(): void {
    const persistence = this.persistenceForm.value;
    this.settingsStepService.addPersistence(persistence);
    this.stepCompletion.emit(new StepCompletion(
      Step.PERSISTENCE,
      true,
      NavigationDirection.FORWARD
    ));
  }

  previous(): void {
    this.stepCompletion.emit(new StepCompletion(
      Step.PERSISTENCE,
      true,
      NavigationDirection.REWIND
    ));
  }

  hasNext(): Boolean {
    return true;
  }
  hasPrevious(): Boolean {
    return true;
  }

  private defineProjections(storageType: string){
    this.projections = (storageType === 'JOURNAL') ? [{
      name: 'Not Applicable',
      value: 'NONE'
    },
    {
      name: 'Event Based',
      value: 'EVENT_BASED'
    }
  ] :
  [{
      name: 'Not Applicable',
      value: 'NONE'
    },
    {
      name: 'Event Based',
      value: 'EVENT_BASED'
    },
    {
      name: 'Operation Based',
      value: 'OPERATION_BASED'
    }
  ];
  }

}

<app-step-title title="Model - Persistence"></app-step-title>
<form [formGroup]="persistenceForm" class="persistence-form">
  <mat-form-field appearance="fill">
    <mat-label>Storage Type</mat-label>
    <mat-select formControlName="storageType">
      <mat-option *ngFor="let type of storageTypes" [value]="type.value">
        {{type.name}}
      </mat-option>
    </mat-select>
  </mat-form-field>
  <mat-form-field appearance="fill">
    <mat-label>Projections</mat-label>
    <mat-select formControlName="projections" [disabled]="!persistenceForm.get('storageType').value">
      <mat-option *ngFor="let proj of projections" [value]="proj.value">
        {{proj.name}}
      </mat-option>
    </mat-select>
  </mat-form-field>
    <mat-label>Use CQRS?</mat-label>
    <mat-button-toggle-group formControlName="useCQRS" style="width: 30%;">
      <mat-button-toggle value="NO">No</mat-button-toggle>
      <mat-button-toggle value="YES">Yes</mat-button-toggle>
    </mat-button-toggle-group>
  <mat-form-field appearance="fill" *ngIf="persistenceForm.get('useCQRS').value === 'NO'" style="padding-top: 8%;">
    <mat-label>Database</mat-label>
    <mat-select formControlName="database">
      <mat-option *ngFor="let database of databases" [value]="database.value">
        {{database.name}}
      </mat-option>
    </mat-select>  </mat-form-field>
  <mat-form-field appearance="fill" *ngIf="persistenceForm.get('useCQRS').value  === 'YES'" style="padding-top: 8%;">
    <mat-label>Command Model Database</mat-label>
    <mat-select formControlName="commandModelDatabase">
      <mat-option *ngFor="let commandModelDatabase of databases" [value]="commandModelDatabase.value">
        {{commandModelDatabase.name}}
      </mat-option>
    </mat-select>
  </mat-form-field>
  <mat-form-field appearance="fill" *ngIf="persistenceForm.get('useCQRS').value === 'YES'">
    <mat-label>Query Model Database</mat-label>
    <mat-select formControlName="queryModelDatabase">
      <mat-option *ngFor="let queryModelDatabase of databases" [value]="queryModelDatabase.value">
        {{queryModelDatabase.name}}
      </mat-option>
    </mat-select>
  </mat-form-field>
</form>

// src/main/frontend/src/routes/persistence.svelte
<script>
	import Select from "svelte-materialify/src/components/Select";
	import Switch from "svelte-materialify/src/components/Switch";
	import CardForm from "../components/CardForm.svelte";
	import { persistenceSettings } from "../stores";

	const storageTypes = [
      {name: "State Store", value: "STATE_STORE"},
      {name: "Journal", value: "JOURNAL"}
	];
	const storageFormat = (val) => storageTypes.find(t => t.value === val).name;
	let projectionsTypes = [
		{name: 'Not Applicable', value: 'NONE'},
		{name: 'Event Based', value: 'EVENT_BASED'},
		{name: 'Operation Based', value: 'OPERATION_BASED'}
	];
	const projectionFormat = (val) => projectionsTypes.find(t => t.value === val).name;
	const databaseTypes = [
      {name: "In Memory", value: "IN_MEMORY"},
      {name: "Postgres", value: "POSTGRES"},
      {name: "HSQLDB", value: "HSQLDB"},
      {name: "MySQL", value: "MYSQL"},
      {name: "YugaByte", value: "YUGA_BYTE"}
    ];
	const databaseFormat = (val) => databaseTypes.find(t => t.value === val).name;

    let storageType = $persistenceSettings ? $persistenceSettings.storageType : "STATE_STORE";
    let useCQRS = $persistenceSettings ? $persistenceSettings.useCQRS : false;
    let projections = $persistenceSettings ? $persistenceSettings.projections : "NONE";
    let database = $persistenceSettings ? $persistenceSettings.database : "IN_MEMORY";
    let commandModelDatabase = $persistenceSettings ? $persistenceSettings.commandModelDatabase : "IN_MEMORY";
	let queryModelDatabase = $persistenceSettings ? $persistenceSettings.queryModelDatabase : "IN_MEMORY";

	$: changedCQRS(useCQRS);
	$: changedStorageType(storageType);

	function changedCQRS(useCQRS) {
		if(!useCQRS) {
			projections = "NONE";
		} 
	}

	function changedStorageType(storageType) {
		if(storageType === "JOURNAL") {
			projectionsTypes = [
				{name: 'Not Applicable', value: 'NONE'},
				{name: 'Event Based', value: 'EVENT_BASED'},
			];
			projections = "NONE";
		} else {
			projectionsTypes = [
				{name: 'Not Applicable', value: 'NONE'},
				{name: 'Event Based', value: 'EVENT_BASED'},
				{name: 'Operation Based', value: 'OPERATION_BASED'}
			];
		}
	}
	$: $persistenceSettings = { storageType, useCQRS, projections, database, commandModelDatabase, queryModelDatabase }
	$: console.log($persistenceSettings);
</script>

<svelte:head>
	<title>Persistence</title>
</svelte:head>

<!-- add newbie tooltips -->
<CardForm title="Persistence" previous="aggregates" next="deployment">
	<Select class="ma-4" mandatory items={storageTypes} bind:value={storageType} format={(val) => storageFormat(val)}>Storage Type</Select>
	<Switch class="ma-4 mb-8" bind:checked={useCQRS}>Use CQRS</Switch>
	<Select disabled={!useCQRS} class="ma-4" mandatory items={projectionsTypes} bind:value={projections} format={(val) => projectionFormat(val)}>Projections</Select>
	{#if useCQRS}
		<Select class="ma-4" mandatory items={databaseTypes} bind:value={commandModelDatabase} format={(val) => databaseFormat(val)}>Command Model Database</Select>
		<Select class="ma-4" mandatory items={databaseTypes} bind:value={queryModelDatabase} format={(val) => databaseFormat(val)}>Query Model Database</Select>
	{:else}
		<Select class="ma-4" mandatory items={databaseTypes} bind:value={database} format={(val) => databaseFormat(val)}>Database</Select>
	{/if}
</CardForm>
